defaults:
  - paths: default
  - env: default
  - misc: default
  - dataset: default
  - evaluator: default
  - vision_model: default
  - pipeline: split_inference
  - codec: default
  - _self_


dataset:
  type: "Detectron2Dataset"
  datacatalog: "MPEGOIV6"
  config:
    root: "/pa/projects/etl-vcm/fcvcm/vcm_testdata/mpeg-oiv6"
    imgs_folder: "images"
    annotation_file: "annotations/mpeg-oiv6-detection-coco.json"
    dataset_name: "mpeg-oiv6-detection"

pipeline:
  type: "image"
  nn_task_part1:
    generate_features_only: True
  output_dir: ${paths._run_root}/${dataset.datacatalog}

