variables:
  UV_INSTALL_DIR: "${CI_PROJECT_DIR}/.local/bin"
  UV_CACHE_DIR: "${CI_PROJECT_DIR}/.uv-cache"
  UV_LINK_MODE: copy

stages:
  - setup
  - static-analysis
  - test
  - doc

.default-before-script: &default-before-script
  - git submodule update --init --recursive
  - export PATH="${UV_INSTALL_DIR}:$PATH"
  - source "${UV_INSTALL_DIR}/env"
  - uv run --no-sync python --version
  - bash scripts/install_uv.sh --no-install --no-weights --cpu

uv-install-py38:
  image: python:3.8-bullseye
  stage: setup
  script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - *default-before-script
  artifacts:
    paths:
      - ".local/"
    expire_in: 1 day
  tags:
    - docker

uv-install-py310:
  image: python:3.10-bullseye
  stage: setup
  script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - *default-before-script
  artifacts:
    paths:
      - ".local/"
    expire_in: 1 day
  tags:
    - docker
ruff-lint:
  stage: static-analysis
  image: python:3.8-bullseye
  before_script:
    - *default-before-script
    - uv pip install -U pip wheel setuptools
    - uv sync --group=dev
  script:
    - uv run --no-sync make check-ruff-lint
  tags:
    - docker

pytest-py38:
  stage: test
  image: python:3.8-bullseye
  dependencies:
    - uv-install-py38
  before_script:
    - apt-get update -y
    - apt-get install -y libgl1-mesa-glx build-essential
    - *default-before-script
    - uv pip install -U pip wheel setuptools
    - bash scripts/install_uv.sh --no-weights --cpu -m "detectron2,yolox,segment_anything,jde"
    - uv sync --inexact --extra=dev
  script:
    - uv run --no-sync pytest
  tags:
    - docker

pytest-py310:
  stage: test
  image: python:3.10-bullseye
  dependencies:
    - uv-install-py310
  before_script:
    - apt-get update -y
    - apt-get install -y libgl1-mesa-glx build-essential
    - *default-before-script
    - uv pip install -U pip wheel setuptools
    - bash scripts/install_uv.sh --no-weights --cpu -m "detectron2,yolox,segment_anything,jde"
    - uv sync --inexact --extra=dev
  script:
    - uv run --no-sync pytest
  tags:
    - docker

pytest-pip-py38:
  stage: test
  image: python:3.8-bullseye
  before_script:
    - apt-get update -y
    - apt-get install -y libgl1-mesa-glx build-essential
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -U pip wheel setuptools
    - pip install torch==2.0.0 torchvision==0.15.1 --index-url https://download.pytorch.org/whl/cpu
    - bash scripts/install.sh --no-weights --cpu -m "detectron2,yolox,segment_anything,jde"
    - pip install -e .[dev,cpu]
  script:
    - pytest
  tags:
    - docker


ruff-format:
  stage: static-analysis
  image: python:3.8-bullseye
  before_script:
    - *default-before-script
    - uv pip install -U pip wheel setuptools
    - uv sync --group=dev
  script:
    - uv run --no-sync make check-ruff-format
  tags:
    - docker

ruff-organize-imports:
  stage: static-analysis
  image: python:3.8-bullseye
  before_script:
    - *default-before-script
    - uv pip install -U pip wheel setuptools
    - uv sync --group=dev
  script:
    - uv run --no-sync make check-ruff-organize-imports
  tags:
    - docker

doc:
  stage: doc
  image: python:3.8-bullseye
  before_script:
    - *default-before-script
    - uv pip install -U pip wheel setuptools
    - uv sync --group=doc
    - cd docs
  script:
    - uv run --no-sync make html
  tags:
    - docker
