variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - "$CI_PROJECT_DIR/.cache/pip"

stages:
  - static-analysis
  - doc


.flake8:
  stage: static-analysis
  image: python:3.8-buster
  before_script:
    - python --version
    - pip install -U pip flake8
  script:
    - flake8 --max-line-length 88 compressai_vision data/mpeg-fcm
  tags:
    - docker



black:
  stage: static-analysis
  image: python:3.8-buster
  before_script:
    - python --version
    - pip install -U pip black
  script:
    - black --check compressai_vision data/mpeg-fcm scripts/metrics
  tags:
    - docker

isort:
  stage: static-analysis
  image: python:3.8-buster
  before_script:
    - python --version
    - pip install -U pip isort
  script:
    - isort compressai_vision data/mpeg-fcm scripts/metrics --check-only
  tags:
    - docker

doc:
  cache: []
  stage: doc
  image: python:3.8-buster
  before_script:
    - python --version
    - pip install -e .[doc]
    - cd docs
  script:
    - make html
  tags:
    - docker