# pyproject.toml
[build-system]
requires = [
    "Pillow>=7.1",
    "matplotlib",
    "pycocotools>=2.0.2",
    "termcolor>=1.1",
    "yacs>=0.1.8",
    "tabulate",
    "cloudpickle",
    "tqdm>4.29.0",
    "tensorboard",
    "fvcore<0.1.6,>=0.1.5",
    "iopath<0.1.10,>=0.1.7",
    "omegaconf<2.4,>=2.1",
    "hydra-core>=1.1",
    "black",
    "packaging",
    "numpy",
    "pyyaml>=5.1",
    "portalocker",
    "antlr4-python3-runtime==4.9.*", 
    "click>=7.1.2",
    "appdirs",
    "toml>=0.10.1",
    "regex>=2020.1.8",
    "pathspec<1,>=0.8.1",
    "mypy-extensions>=0.4.3",
    "contourpy>=1.0.1",
    "cycler>=0.10",
    "fonttools>=4.22.0",
    "kiwisolver>=1.3.1",
    "pyparsing>=2.3.1",
    "python-dateutil>=2.7",
    "six>=1.5",
    "absl-py>=0.4",
    "grpcio>=1.48.2",
    "markdown>=2.6.8",
    "protobuf!=4.24.0,>=3.19.6",
    "setuptools>=41.0.0",
    "tensorboard-data-server<0.8.0,>=0.7.0",
    "werkzeug>=1.0.1",
    "MarkupSafe>=2.1.1",
]
build-backend = "setuptools.build_meta"