arch: "faster_rcnn_R_50_FPN_3x"

model_root_path: "default" # replace with your model root path [default=compressai_vision_repo]

faster_rcnn_R_50_FPN_3x:
  model_path_prefix: ${..model_root_path}
  cfg: "models/detectron2/configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
  weights: "weights/detectron2/COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  integer_conv_weight: False
  splits : "r2" #, "c2" or "fpn"

faster_rcnn_X_101_32x8d_FPN_3x:
  model_path_prefix: ${..model_root_path}
  cfg: "models/detectron2/configs/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml"
  weights: "weights/detectron2/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x/139173657/model_final_68b088.pkl"
  integer_conv_weight: False
  splits : "fpn" #, "c2" or "r2"
  hyper_params:
    update: False 
    conf_threshold: 0.05
    max_dets: 100

mask_rcnn_R_50_FPN_3x:
  model_path_prefix: ${..model_root_path}
  cfg: "models/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
  weights: "weights/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
  integer_conv_weight: False
  splits : "r2" #, "c2" or "fpn"

mask_rcnn_X_101_32x8d_FPN_3x:
  model_path_prefix: ${..model_root_path}
  cfg: "models/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml"
  weights: "weights/detectron2/COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x/139653917/model_final_2d9806.pkl"
  integer_conv_weight: False
  splits : "fpn" #, "c2" or "r2"

panoptic_rcnn_R_101_FPN_3x:
  model_path_prefix: ${..model_root_path}
  cfg: "models/detectron2/configs/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml"
  weights: "weights/detectron2/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x/139514519/model_final_cafdb1.pkl"
  integer_conv_weight: False
  splits : "fpn"

sam_vit_h_4b8939:
  model_path_prefix: ${..model_root_path}
  cfg: "Built-in configurations"
  weights: "weights/segment_anything/sam_vit_h_4b8939.pth"
  splits: "imgenc"

sam2_hiera_image_model:
  model_path_prefix: ${..model_root_path}
  cfg: "models/sam2/sam2/configs/sam2.1/sam2.1_hiera_b+.yaml"
  weights: "weights/sam2/sam2.1_hiera_base_plus.pt"
  # weights: "weights/sam2/sam2.1_hiera_large.pt"
  # weights: "weights/sam2/sam2.1_hiera_small.pt"
  # weights: "weights/sam2/sam2.1_hiera_tiny.pt"
  splits: "backbone"

sam2_hiera_video_model:
  model_path_prefix: ${..model_root_path}
  cfg: "models/sam2/sam2/configs/sam2.1/sam2.1_hiera_b+.yaml"
  weights: "weights/sam2/sam2.1_hiera_base_plus.pt"
  # weights: "weights/sam2/sam2.1_hiera_large.pt"
  # weights: "weights/sam2/sam2.1_hiera_small.pt"
  # weights: "weights/sam2/sam2.1_hiera_tiny.pt"
  splits: "backbone"

jde_1088x608:
  model_path_prefix: ${..model_root_path}
  cfg: "models/Towards-Realtime-MOT/cfg/yolov3_1088x608.cfg"
  weights: "weights/jde/jde.1088x608.uncertainty.pt"
  integer_conv_weight: False
  hyper_params:
    update: False
    conf_threshold: 0.5
  splits : [36, 61, 74] # MPEG FCM TEST with JDE on TVD
  #splits : [105, 90, 75] # MPEG FCM TEST with JDE on HiEve

yolox_darknet53:
  model_path_prefix: ${..model_root_path}
  cfg: "Built-in configurations"
  num_classes: 80
  conf_thres: 0.001
  nms_thres: 0.65
  weights: "weights/yolox/darknet53/yolox_darknet.pth"
  splits: "l13" #"l37"
  squeeze_at_split: False

rtmo_multi_person_pose_estimation:
  model_path_prefix: ${..model_root_path}
  cfg: "models/mmpose/configs/body_2d_keypoint/rtmo/coco/rtmo-l_16xb16-600e_coco-640x640.py"
  weights: "weights/mmpose/rtmo_coco/rtmo-l_16xb16-600e_coco-640x640-516a421f_20231211.pth"
  splits: "backbone"

fasterrcnn_mobilenet_v3_large_320_fpn:
  model_path_prefix: ${..model_root_path}
  cfg: "torchvision built-in configuration"
  weights: "DEFAULT"
  weights_url: "https://download.pytorch.org/models/fasterrcnn_mobilenet_v3_large_320_fpn-907ea3f9.pth"
  weights_backbone: null
  progress: True
  splits: "fpn"
  backbone_feature_keys: ["0", "1", "pool"]
  split_layer_names: ["fpn0", "fpn1", "fpn_pool"]
  min_size: 320
  max_size: 640
  rpn_pre_nms_top_n_test: 150
  rpn_post_nms_top_n_test: 150
  rpn_score_thresh: 0.05
  box_score_thresh: null
  box_nms_thresh: null
  box_detections_per_img: null

lraspp_mobilenet_v3_large:
  model_path_prefix: ${..model_root_path}
  cfg: "torchvision built-in configuration"
  weights: "DEFAULT"
  weights_url: "https://download.pytorch.org/models/lraspp_mobilenet_v3_large-d234d4ea.pth"
  weights_backbone: null
  progress: True
  use_weights_transforms: True
  splits: "backbone" # alternative candidate: "logits"

efficientvit_sam_l0:
  model_path_prefix: ${..model_root_path}
  cfg: "efficientvit built-in configuration"
  weights: "weights/efficientvit/sam/l0.pt"
  pretrained: True
  splits: "imgenc"
  prompt_type: "point_file" # official COCO benchmark: "box_from_detector"
  source_json_file: null
  prompt_score_threshold: null
  max_prompts_per_image: null

efficientvit_sam_l1:
  model_path_prefix: ${..model_root_path}
  cfg: "efficientvit built-in configuration"
  weights: "weights/efficientvit/sam/l1.pt"
  pretrained: True
  splits: "imgenc"
  prompt_type: "point_file"
  source_json_file: null
  prompt_score_threshold: null
  max_prompts_per_image: null

efficientvit_sam_l2:
  model_path_prefix: ${..model_root_path}
  cfg: "efficientvit built-in configuration"
  weights: "weights/efficientvit/sam/l2.pt"
  pretrained: True
  splits: "imgenc"
  prompt_type: "point_file"
  source_json_file: null
  prompt_score_threshold: null
  max_prompts_per_image: null

efficientvit_sam_xl0:
  model_path_prefix: ${..model_root_path}
  cfg: "efficientvit built-in configuration"
  weights: "weights/efficientvit/sam/xl0.pt"
  pretrained: True
  splits: "imgenc"
  prompt_type: "point_file"
  source_json_file: null
  prompt_score_threshold: null
  max_prompts_per_image: null

efficientvit_sam_xl1:
  model_path_prefix: ${..model_root_path}
  cfg: "efficientvit built-in configuration"
  weights: "weights/efficientvit/sam/xl1.pt"
  pretrained: True
  splits: "imgenc"
  prompt_type: "point_file"
  source_json_file: null
  prompt_score_threshold: null
  max_prompts_per_image: null
