arch: "faster_rcnn_R_50_FPN_3x"

model_root_path: "default" # replace with your model root path [default=compressai_vision_repo]

faster_rcnn_R_50_FPN_3x:
  model_path_prefix: ${..model_root_path}
  cfg: "models/detectron2/configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
  weights: "weights/detectron2/COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  integer_conv_weight: False
  splits : "r2" #, "c2" or "fpn"

faster_rcnn_X_101_32x8d_FPN_3x:
  model_path_prefix: ${..model_root_path}
  cfg: "models/detectron2/configs/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml"
  weights: "weights/detectron2/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x/139173657/model_final_68b088.pkl"
  integer_conv_weight: False
  splits : "fpn" #, "c2" or "r2"
  hyper_params:
    update: False 
    conf_threshold: 0.05
    max_dets: 100

mask_rcnn_R_50_FPN_3x:
  model_path_prefix: ${..model_root_path}
  cfg: "models/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
  weights: "weights/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
  integer_conv_weight: False
  splits : "r2" #, "c2" or "fpn"

sam_vit_h_4b8939:
  model_path_prefix: ${..model_root_path}
  cfg: "Built-in configurations"
  weights: "weights/segment_anything/sam_vit_h_4b8939.pth"
  splits: "imgenc" 

mask_rcnn_X_101_32x8d_FPN_3x:
  model_path_prefix: ${..model_root_path}
  cfg: "models/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml"
  weights: "weights/detectron2/COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x/139653917/model_final_2d9806.pkl"
  integer_conv_weight: False
  splits : "fpn" #, "c2" or "r2"

panoptic_rcnn_R_101_FPN_3x:
  model_path_prefix: ${..model_root_path}
  cfg: "models/detectron2/configs/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml"
  weights: "weights/detectron2/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x/139514519/model_final_cafdb1.pkl"
  integer_conv_weight: False
  splits : "fpn"

jde_1088x608:
  model_path_prefix: ${..model_root_path}
  cfg: "models/Towards-Realtime-MOT/cfg/yolov3_1088x608.cfg"
  weights: "weights/jde/jde.1088x608.uncertainty.pt"
  integer_conv_weight: False
  hyper_params:
    update: False
    conf_threshold: 0.5
  splits : [36, 61, 74] # MPEG FCM TEST with JDE on TVD
  #splits : [105, 90, 75] # MPEG FCM TEST with JDE on HiEve

yolox_darknet53:
  model_path_prefix: ${..model_root_path}
  cfg: "Built-in configurations"
  num_classes: 80
  conf_thres: 0.001
  nms_thres: 0.65
  weights: "weights/yolox/darknet53/yolox_darknet.pth"
  splits: "l13" #"l37"
  squeeze_at_split: False

rtmo_multi_person_pose_estimation:
  model_path_prefix: ${..model_root_path}
  cfg: "models/mmpose/configs/body_2d_keypoint/rtmo/coco/rtmo-l_16xb16-600e_coco-640x640.py"
  weights: "weights/mmpose/rtmo_coco/rtmo-l_16xb16-600e_coco-640x640-516a421f_20231211.pth"
  splits: "backbone"
