type: 'DefaultDataset'
datacatalog: 'COCO'
config:
  root: '/data/dataset'
  imgs_folder: 'valid'
  annotation_file: "sample.json"
  dataset_name: "sample_dataset"
settings:
  patch_size: [512, 512]
  ret_name: False
  use_BGR: False
transforms:
  - "Resize": {size: "${....settings.patch_size}"}
  - "ToTensor": {}
loader:
  shuffle: False
  batch_size: 1
  num_workers: 2


