type: 'DefaultDataset'
datacatalog: 'COCO'
config:
  root: '/data/dataset'
  dataset_name: "sample_dataset"
  imgs_folder: 'images'
  annotation_file: "annotations/${.dataset_name}.json"
  seqinfo: "seqinfo.ini"
  ext: "png"
settings:
  patch_size: [512, 512]
  ret_name: False
  use_BGR: False
transforms:
  - "Resize": {size: "${....settings.patch_size}"}
  - "ToTensor": {}
loader:
  shuffle: False
  batch_size: 1
  num_workers: 2


