name: Static Analysis

on: [push, pull_request]

jobs:
  static_analysis:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.8"
    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: recursive

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install the project
      run: |
        uv pip install -U pip wheel setuptools
        uv sync --group=dev
     
    - name: Run static analysis  
      run: make static-analysis
