name: publish documentation

on:
  push:
    branches:
      - main
jobs:
  docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: publish documentation
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: recursive

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.8'

      - name: Install doc dependencies and build docs
        run: |
          uv sync --group=doc
          cd docs
          uv run --no-sync make html

      - name: Init repo for generated files
        run: |
          cd docs/_build/html
          git init
          touch .nojekyll
          git add --all
          git config --local user.email "compressai@interdigital.com"
          git config --local user.name "CompressAI"
          git commit -m "deploy"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
