name: basic install 

on: [push, pull_request]
jobs:
  test-install:
    runs-on: ubuntu-latest
    name: basic install of compressai-vision with uv (torch cpu)
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: install project with uv
        run: |
          uv pip install -U pip wheel setuptools
          bash scripts/install_uv.sh --no-weights --cpu -m "detectron2,yolox,segment_anything,jde"

