name: Test (pip)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-pip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libgl1-mesa-glx build-essential

      - name: Create and activate virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -U pip wheel setuptools
          bash scripts/install.sh --no-weights --cpu -m "detectron2,yolox,segment_anything,jde"
          pip install -e .[dev,cpu]

      - name: Run pytest
        run: |
          source venv/bin/activate
          pytest
